#!/bin/bash

# This script prints a color gradient to the terminal.
# It uses 256 colors and the 24-bit color mode.
# If you see a continuous gradient from black to white, your terminal
# supports 24-bit colors.

awk 'BEGIN{
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
}'

echo "If you see a continuous color gradient, suggeting your terminal supports truecolors"

